# Generated by Django 4.2.9 on 2024-02-01 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_user_and_more'),
        ('wars', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='accounts.employee')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='wars.menu')),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='wars.war')),
            ],
        ),
    ]
